##
## EPITECH PROJECT, 2021
## B-OOP-400-BDX-4-1-arcade-geoffroy-yann
## File description:
## Makefile
##

all: server client

server:
	make -C ./server/

clean:
		make clean -C ./server/

fclean:
		make fclean -C	./server/
re:	fclean all

.PHONY:	all server client clean fclean re